# Replace with the path to a runfile to act as the entrypoint for the application. Not needed if programming an API.
# When running, the function run() will be called with the arguments from the command line passed to the function in the form of a string array
entrypoint: runfiles/entrypoint.es
# Set to true if project is an API
is-api: false
# C script to run when installing after installer script
# Can be used to set up config, among other things
#installer-script: install.c
# If set to true, the installer will not run, and will let the installer script do everything
installer-script-replace: false
# Change to the folder where components are kept
components: components/
# Change to the folder where objects are kept
objects: objects/
# Change to the folder where runfiles are kept
runfiles: runfiles/
# Change to the folder where APIs are kept. Only needed if APIs are used.
#apis: apis/
# DO NOT CHANGE
config-version: 1